module.exports = Object.freeze({
    Basic: {
        Code: 0,
        Name: 'basic',
        Module: 'basic',
        Description: 'basic_right',
        App: 'Basic',
    },
    AdminViewAdminOverview: {
        Code: 100,
        Name: 'admin_view_admin_overview',
        Module: 'overview',
        Description: 'can_view_admin_overview',
        App: 'Admin',
    },
    AdminViewNlpEngines: {
        Code: 110,
        Name: 'admin_view_nlp_engines',
        Module: 'nlp_engines',
        Description: 'can_view_nlp_engines',
        App: 'Admin',
    },
    AdminCreateNlpEngines: {
        Code: 111,
        Name: 'admin_create_nlp_engines',
        Module: 'nlp_engines',
        Description: 'can_create_nlp_engines',
        App: 'Admin',
    },
    AdminUpdateNlpEngines: {
        Code: 112,
        Name: 'admin_update_nlp_engines',
        Module: 'nlp_engines',
        Description: 'can_update_nlp_engines',
        App: 'Admin',
    },
    AdminDeleteNlpEngines: {
        Code: 113,
        Name: 'admin_delete_nlp_engines',
        Module: 'nlp_engines',
        Description: 'can_delete_nlp_engines',
        App: 'Admin',
    },
    AdminViewSystemEntities: {
        Code: 120,
        Name: 'admin_view_system_entities',
        Module: 'system_entities',
        Description: 'can_view_system_entities',
        App: 'Admin',
    },
    AdminCreateSystemEntities: {
        Code: 121,
        Name: 'admin_create_system_entities',
        Module: 'system_entities',
        Description: 'can_create_system_entities',
        App: 'Admin',
    },
    AdminUpdateSystemEntities: {
        Code: 122,
        Name: 'admin_update_system_entities',
        Module: 'system_entities',
        Description: 'can_update_system_entities',
        App: 'Admin',
    },
    AdminDeleteSystemEntities: {
        Code: 123,
        Name: 'admin_delete_system_entities',
        Module: 'system_entities',
        Description: 'can_delete_system_entities',
        App: 'Admin',
    },
    AdminViewSystemTeenCodes: {
        Code: 130,
        Name: 'admin_view_system_teen_codes',
        Module: 'system_teen_codes',
        Description: 'can_view_system_teen_codes',
        App: 'Admin',
    },
    AdminCreateSystemTeenCodes: {
        Code: 131,
        Name: 'admin_create_system_teen_codes',
        Module: 'system_teen_codes',
        Description: 'can_create_system_teen_codes',
        App: 'Admin',
    },
    AdminUpdateSystemTeenCodes: {
        Code: 132,
        Name: 'admin_update_system_teen_codes',
        Module: 'system_teen_codes',
        Description: 'can_update_system_teen_codes',
        App: 'Admin',
    },
    AdminDeleteSystemTeenCodes: {
        Code: 133,
        Name: 'admin_delete_system_teen_codes',
        Module: 'system_teen_codes',
        Description: 'can_delete_system_teen_codes',
        App: 'Admin',
    },
    AdminViewSystemStopWords: {
        Code: 140,
        Name: 'admin_view_system_stop_words',
        Module: 'system_stop_words',
        Description: 'can_view_system_stop_words',
        App: 'Admin',
    },
    AdminCreateSystemStopWords: {
        Code: 141,
        Name: 'admin_create_system_stop_words',
        Module: 'system_stop_words',
        Description: 'can_create_system_stop_words',
        App: 'Admin',
    },
    AdminUpdateSystemStopWords: {
        Code: 142,
        Name: 'admin_update_system_stop_words',
        Module: 'system_stop_words',
        Description: 'can_update_system_stop_words',
        App: 'Admin',
    },
    AdminDeleteSystemStopWords: {
        Code: 143,
        Name: 'admin_delete_system_stop_words',
        Module: 'system_stop_words',
        Description: 'can_delete_system_stop_words',
        App: 'Admin',
    },
    AdminViewUsers: {
        Code: 150,
        Name: 'admin_view_users',
        Module: 'users',
        Description: 'can_view_users',
        App: 'Admin',
    },
    AdminCreateUsers: {
        Code: 151,
        Name: 'admin_create_users',
        Module: 'users',
        Description: 'can_create_users',
        App: 'Admin',
    },
    AdminUpdateUsers: {
        Code: 152,
        Name: 'admin_update_users',
        Module: 'users',
        Description: 'can_update_users',
        App: 'Admin',
    },
    AdminActivateUsers: {
        Code: 153,
        Name: 'admin_activate_users',
        Module: 'users',
        Description: 'can_activate_users',
        App: 'Admin',
    },
    AdminDeactivateUsers: {
        Code: 154,
        Name: 'admin_deactivate_users',
        Module: 'users',
        Description: 'can_deactivate_users',
        App: 'Admin',
    },
    AdminDeleteUsers: {
        Code: 155,
        Name: 'admin_delete_users',
        Module: 'users',
        Description: 'can_delete_users',
        App: 'Admin',
    },
    AdminViewOrganizations: {
        Code: 160,
        Name: 'admin_view_organizations',
        Module: 'organizations',
        Description: 'can_view_organizations',
        App: 'Admin',
    },
    AdminCreateOrganizations: {
        Code: 161,
        Name: 'admin_create_organizations',
        Module: 'organizations',
        Description: 'can_create_organizations',
        App: 'Admin',
    },
    AdminUpdateOrganizations: {
        Code: 162,
        Name: 'admin_update_organizations',
        Module: 'organizations',
        Description: 'can_update_organizations',
        App: 'Admin',
    },
    AdminActivateOrganizations: {
        Code: 163,
        Name: 'admin_activate_organizations',
        Module: 'organizations',
        Description: 'can_activate_organizations',
        App: 'Admin',
    },
    AdminDeactivateOrganizations: {
        Code: 164,
        Name: 'admin_deactivate_organizations',
        Module: 'organizations',
        Description: 'can_deactivate_organizations',
        App: 'Admin',
    },
    AdminDeleteOrganizations: {
        Code: 165,
        Name: 'admin_delete_organizations',
        Module: 'organizations',
        Description: 'can_delete_organizations',
        App: 'Admin',
    },
    AdminViewRoles: {
        Code: 170,
        Name: 'admin_view_roles',
        Module: 'roles',
        Description: 'can_view_roles',
        App: 'Admin',
    },
    AdminCreateRoles: {
        Code: 171,
        Name: 'admin_create_roles',
        Module: 'roles',
        Description: 'can_create_roles',
        App: 'Admin',
    },
    AdminUpdateRoles: {
        Code: 172,
        Name: 'admin_update_roles',
        Module: 'roles',
        Description: 'can_update_roles',
        App: 'Admin',
    },
    AdminActivateRoles: {
        Code: 173,
        Name: 'admin_activate_roles',
        Module: 'roles',
        Description: 'can_activate_roles',
        App: 'Admin',
    },
    AdminDeactivateRoles: {
        Code: 174,
        Name: 'admin_deactivate_roles',
        Module: 'roles',
        Description: 'can_deactivate_roles',
        App: 'Admin',
    },
    AdminDeleteRoles: {
        Code: 175,
        Name: 'admin_delete_roles',
        Module: 'roles',
        Description: 'can_delete_roles',
        App: 'Admin',
    },
    AdminViewLocalizations: {
        Code: 180,
        Name: 'admin_view_localizations',
        Module: 'localizations',
        Description: 'can_view_localizations',
        App: 'Admin',
    },
    AdminCreateLocalizations: {
        Code: 181,
        Name: 'admin_create_localizations',
        Module: 'localizations',
        Description: 'can_create_localizations',
        App: 'Admin',
    },
    AdminUpdateLocalizations: {
        Code: 182,
        Name: 'admin_update_localizations',
        Module: 'localizations',
        Description: 'can_update_localizations',
        App: 'Admin',
    },
    AdminDeleteLocalizations: {
        Code: 183,
        Name: 'admin_delete_localizations',
        Module: 'localizations',
        Description: 'can_delete_localizations',
        App: 'Admin',
    },
    AdminImportLocalizations: {
        Code: 184,
        Name: 'admin_import_localizations',
        Module: 'localizations',
        Description: 'can_import_localizations',
        App: 'Admin',
    },
    AdminExportLocalizations: {
        Code: 185,
        Name: 'admin_export_localizations',
        Module: 'localizations',
        Description: 'can_export_localizations',
        App: 'Admin',
    },
    AdminReloadCaches: {
        Code: 186,
        Name: 'admin_reload_caches',
        Module: 'localizations',
        Description: 'can_reload_caches',
        App: 'Admin',
    },
    AdminViewTutorials: {
        Code: 190,
        Name: 'admin_view_tutorials',
        Module: 'tutorials',
        Description: 'can_view_tutorials',
        App: 'Admin',
    },
    AdminCreateTutorials: {
        Code: 191,
        Name: 'admin_create_tutorials',
        Module: 'tutorials',
        Description: 'can_create_tutorials',
        App: 'Admin',
    },
    AdminUpdateTutorials: {
        Code: 192,
        Name: 'admin_update_tutorials',
        Module: 'tutorials',
        Description: 'can_update_tutorials',
        App: 'Admin',
    },
    AdminDeleteTutorials: {
        Code: 193,
        Name: 'admin_delete_tutorials',
        Module: 'tutorials',
        Description: 'can_delete_tutorials',
        App: 'Admin',
    },
    AdminViewListOfActionLogs: {
        Code: 200,
        Name: 'admin_view_list_of_action_logs',
        Module: 'action_logs',
        Description: 'can_view_list_of_action_logs',
        App: 'Admin',
    },
    AdminViewListOfQcLogs: {
        Code: 201,
        Name: 'admin_view_list_of_qc_logs',
        Module: 'qc_logs',
        Description: 'can_view_list_of_qc_logs',
        App: 'Admin',
    },
    AdminViewFeedbacks: {
        Code: 210,
        Name: 'admin_view_feedbacks',
        Module: 'feedbacks',
        Description: 'can_view_feedbacks',
        App: 'Admin',
    },
    AdminUpdateFeedback: {
        Code: 211,
        Name: 'admin_update_feedback',
        Module: 'feedbacks',
        Description: 'can_update_feedback',
        App: 'Admin',
    },
    AdminDeleteFeedback: {
        Code: 212,
        Name: 'admin_delete_feedback',
        Module: 'feedbacks',
        Description: 'can_delete_feedback',
        App: 'Admin',
    },
    BotViewBasicSettings: {
        Code: 400,
        Name: 'bot_view_basic_settings',
        Module: 'settings',
        Description: 'can_view_basic_settings',
        App: 'Virtual Agent',
    },
    BotViewIntentSettings: {
        Code: 401,
        Name: 'bot_view_intent_settings',
        Module: 'settings',
        Description: 'can_view_intent_settings',
        App: 'Virtual Agent',
    },
    BotViewConfidenceRangeSettings: {
        Code: 402,
        Name: 'bot_view_confidence_range_settings',
        Module: 'settings',
        Description: 'can_view_confidence_range_settings',
        App: 'Virtual Agent',
    },
    BotViewAudioChannelSettings: {
        Code: 403,
        Name: 'bot_view_audio_channel_settings',
        Module: 'settings',
        Description: 'can_view_audio_channel_settings',
        App: 'Virtual Agent',
    },
    BotTrainNlp: {
        Code: 410,
        Name: 'bot_train_nlp',
        Module: 'nlp_actions',
        Description: 'can_train_nlp',
        App: 'Virtual Agent',
    },
    BotTestSingleSentence: {
        Code: 411,
        Name: 'bot_test_single_sentence',
        Module: 'nlp_actions',
        Description: 'can_test_single_sentence',
        App: 'Virtual Agent',
    },
    BotTestMultipleSentences: {
        Code: 412,
        Name: 'bot_test_multiple_sentences',
        Module: 'nlp_actions',
        Description: 'can_test_multiple_sentences',
        App: 'Virtual Agent',
    },
    BotTestNlpWithContext: {
        Code: 413,
        Name: 'bot_test_nlp_with_context',
        Module: 'nlp_actions',
        Description: 'can_test_nlp_with_context',
        App: 'Virtual Agent',
    },
    BotViewOverview: {
        Code: 420,
        Name: 'bot_view_overview',
        Module: 'overview',
        Description: 'can_view_overview',
        App: 'Virtual Agent',
    },
    BotViewSamples: {
        Code: 430,
        Name: 'bot_view_samples',
        Module: 'samples',
        Description: 'can_view_samples',
        App: 'Virtual Agent',
    },
    BotCreateSamples: {
        Code: 431,
        Name: 'bot_create_samples',
        Module: 'samples',
        Description: 'can_create_samples',
        App: 'Virtual Agent',
    },
    BotUpdateSamples: {
        Code: 432,
        Name: 'bot_update_samples',
        Module: 'samples',
        Description: 'can_update_samples',
        App: 'Virtual Agent',
    },
    BotDeleteSamples: {
        Code: 433,
        Name: 'bot_delete_samples',
        Module: 'samples',
        Description: 'can_delete_samples',
        App: 'Virtual Agent',
    },
    BotUploadSamples: {
        Code: 434,
        Name: 'bot_upload_samples',
        Module: 'samples',
        Description: 'can_upload_samples',
        App: 'Virtual Agent',
    },
    BotDowloadSamples: {
        Code: 435,
        Name: 'bot-download_samples',
        Module: 'samples',
        Description: 'can_dowload_samples',
        App: 'Virtual Agent',
    },
    BotViewIntents: {
        Code: 440,
        Name: 'bot_view_intents',
        Module: 'intents',
        Description: 'can_view_intents',
        App: 'Virtual Agent',
    },
    BotCreateIntents: {
        Code: 441,
        Name: 'bot_create_intents',
        Module: 'intents',
        Description: 'can_create_intents',
        App: 'Virtual Agent',
    },
    BotUpdateIntents: {
        Code: 442,
        Name: 'bot_update_intents',
        Module: 'intents',
        Description: 'can_update_intents',
        App: 'Virtual Agent',
    },
    BotDeleteIntents: {
        Code: 443,
        Name: 'bot_delete_intents',
        Module: 'intents',
        Description: 'can_delete_intents',
        App: 'Virtual Agent',
    },
    BotUploadIntents: {
        Code: 444,
        Name: 'bot_upload_intents',
        Module: 'intents',
        Description: 'can_upload_intents',
        App: 'Virtual Agent',
    },
    BotCommentIntents: {
        Code: 445,
        Name: 'bot_comment_intents',
        Module: 'intents',
        Description: 'can_comment_intents',
        App: 'Virtual Agent',
    },
    BotViewEntityTypes: {
        Code: 450,
        Name: 'bot_view_entity_types',
        Module: 'entity_types',
        Description: 'can_view_entity_types',
        App: 'Virtual Agent',
    },
    BotCreateEntityTypes: {
        Code: 451,
        Name: 'bot_create_entity_types',
        Module: 'entity_types',
        Description: 'can_create_entity_types',
        App: 'Virtual Agent',
    },
    BotUpdateEntityTypes: {
        Code: 452,
        Name: 'bot_update_entity_types',
        Module: 'entity_types',
        Description: 'can_update_entity_types',
        App: 'Virtual Agent',
    },
    BotDeleteEntityTypes: {
        Code: 453,
        Name: 'bot_delete_entity_types',
        Module: 'entity_types',
        Description: 'can_delete_entity_types',
        App: 'Virtual Agent',
    },
    BotViewNlpKeywords: {
        Code: 460,
        Name: 'bot_view_nlp_keywords',
        Module: 'nlp_keywords',
        Description: 'can_view_nlp_keywords',
        App: 'Virtual Agent',
    },
    BotCreateNlpKeywords: {
        Code: 461,
        Name: 'bot_create_nlp_keywords',
        Module: 'nlp_keywords',
        Description: 'can_create_nlp_keywords',
        App: 'Virtual Agent',
    },
    BotUpdateNlpKeywords: {
        Code: 462,
        Name: 'bot_update_nlp_keywords',
        Module: 'nlp_keywords',
        Description: 'can_update_nlp_keywords',
        App: 'Virtual Agent',
    },
    BotDeleteNlpKeywords: {
        Code: 463,
        Name: 'bot_delete_nlp_keywords',
        Module: 'nlp_keywords',
        Description: 'can_delete_nlp_keywords',
        App: 'Virtual Agent',
    },
    BotUploadNlpKeywords: {
        Code: 464,
        Name: 'bot_upload_nlp_keywords',
        Module: 'nlp_keywords',
        Description: 'can_upload_nlp_keywords',
        App: 'Virtual Agent',
    },
    BotViewStopWords: {
        Code: 470,
        Name: 'bot_view_stop_words',
        Module: 'stop_words',
        Description: 'can_view_stop_words',
        App: 'Virtual Agent',
    },
    BotCreateStopWords: {
        Code: 471,
        Name: 'bot_create_stop_words',
        Module: 'stop_words',
        Description: 'can_create_stop_words',
        App: 'Virtual Agent',
    },
    BotUpdateStopWords: {
        Code: 472,
        Name: 'bot_update_stop_words',
        Module: 'stop_words',
        Description: 'can_update_stop_words',
        App: 'Virtual Agent',
    },
    BotDeleteStopWords: {
        Code: 473,
        Name: 'bot_delete_stop_words',
        Module: 'stop_words',
        Description: 'can_delete_stop_words',
        App: 'Virtual Agent',
    },
    BotViewTeenCodes: {
        Code: 480,
        Name: 'bot_view_teen_codes',
        Module: 'teen_codes',
        Description: 'can_view_teen_codes',
        App: 'Virtual Agent',
    },
    BotCreateTeenCodes: {
        Code: 481,
        Name: 'bot_create_teen_codes',
        Module: 'teen_codes',
        Description: 'can_create_teen_codes',
        App: 'Virtual Agent',
    },
    BotUpdateTeenCodes: {
        Code: 482,
        Name: 'bot_update_teen_codes',
        Module: 'teen_codes',
        Description: 'can_update_teen_codes',
        App: 'Virtual Agent',
    },
    BotDeleteTeenCodes: {
        Code: 483,
        Name: 'bot_delete_teen_codes',
        Module: 'teen_codes',
        Description: 'can_delete_teen_codes',
        App: 'Virtual Agent',
    },
    BotViewTestingHistory: {
        Code: 490,
        Name: 'bot_view_testing_history',
        Module: 'testing_history',
        Description: 'can_view_testing_history',
        App: 'Virtual Agent',
    },
    BotUpdateTestingHistory: {
        Code: 491,
        Name: 'bot_update_testing_history',
        Module: 'testing_history',
        Description: 'can_update_testing_history',
        App: 'Virtual Agent',
    },
    BotViewTrainingLogs: {
        Code: 500,
        Name: 'bot_view_training_logs',
        Module: 'training_logs',
        Description: 'can_view_training_logs',
        App: 'Virtual Agent',
    },
    BotViewRetrainDatas: {
        Code: 510,
        Name: 'bot_view_retrain_datas',
        Module: 'retrain_data',
        Description: 'can_view_retrain_datas',
        App: 'Virtual Agent',
    },
    BotUpdateRetrainData: {
        Code: 511,
        Name: 'bot_update_retrain_data',
        Module: 'retrain_data',
        Description: 'can_update_retrain_data',
        App: 'Virtual Agent',
    },
    BotDeleteRetrainData: {
        Code: 512,
        Name: 'bot_delete_retrain_data',
        Module: 'retrain_data',
        Description: 'can_delete_retrain_data',
        App: 'Virtual Agent',
    },
    BotAddRetrainDataToSamples: {
        Code: 513,
        Name: 'bot_add_retrain_data_to_samples',
        Module: 'retrain_data',
        Description: 'can_add_retrain_data_to_samples',
        App: 'Virtual Agent',
    },
    BotImportNlpDataset: {
        Code: 520,
        Name: 'bot_import_nlp_dataset',
        Module: 'import_export_nlp_dataset',
        Description: 'can_import_nlp_dataset',
        App: 'Virtual Agent',
    },
    BotExportNlpDataset: {
        Code: 521,
        Name: 'bot_export_nlp_dataset',
        Module: 'import_export_nlp_dataset',
        Description: 'can_export_nlp_dataset',
        App: 'Virtual Agent',
    },
    BotIntegrateWithFacebook: {
        Code: 530,
        Name: 'bot_integrate_with_facebook',
        Module: 'integrations',
        Description: 'can_integrate_with_facebook',
        App: 'Virtual Agent',
    },
    BotIntegrateWithWeb: {
        Code: 531,
        Name: 'bot_integrate_with_web',
        Module: 'integrations',
        Description: 'can_integrate_with_web',
        App: 'Virtual Agent',
    },
    BotIntegrateWithKore: {
        Code: 532,
        Name: 'bot_integrate_with_kore',
        Module: 'integrations',
        Description: 'can_integrate_with_kore',
        App: 'Virtual Agent',
    },
    BotViewIntegration: {
        Code: 533,
        Name: 'bot_view_integration',
        Module: 'integrations',
        Description: 'can_view_integration',
        App: 'Virtual Agent',
    },
    BotViewPrebuiltDomains: {
        Code: 540,
        Name: 'bot_view_prebuilt_domains',
        Module: 'prebuilt domains',
        Description: 'can_view_prebuilt_domains',
        App: 'Virtual Agent',
    },
    BotImportPrebuiltDomains: {
        Code: 541,
        Name: 'bot_import_prebuilt_domains',
        Module: 'prebuilt domains',
        Description: 'can_import_prebuilt_domains',
        App: 'Virtual Agent',
    },
    BotViewBot: {
        Code: 550,
        Name: 'bot_view_bot',
        Module: 'bots',
        Description: 'can_view_bot',
        App: 'Virtual Agent',
    },
    BotCreateBot: {
        Code: 551,
        Name: 'bot_create_bot',
        Module: 'bots',
        Description: 'can_create_bot',
        App: 'Virtual Agent',
    },
    BotUpdateBot: {
        Code: 552,
        Name: 'bot_update_bot',
        Module: 'bots',
        Description: 'can_update_bot',
        App: 'Virtual Agent',
    },
    BotDeleteBot: {
        Code: 553,
        Name: 'bot_detele_bot',
        Module: 'bots',
        Description: 'can_delete_bot',
        App: 'Virtual Agent',
    },
    BotCreateChildBot: {
        Code: 554,
        Name: 'bot_create_child_bot',
        Module: 'bots',
        Description: 'can_create_child_bot',
        App: 'Virtual Agent',
    },
    BotGetResponse: {
        Code: 560,
        Name: 'bot_get_response',
        Module: 'response',
        Description: 'can_get_response',
        App: 'Virtual Agent',
    },
    BotCreateResponse: {
        Code: 561,
        Name: 'bot_create_response',
        Module: 'response',
        Description: 'can_create_response',
        App: 'Virtual Agent',
    },
    BotUpdateResponse: {
        Code: 562,
        Name: 'bot_update_response',
        Module: 'response',
        Description: 'can_update_response',
        App: 'Virtual Agent',
    },
    BotDeleteResponse: {
        Code: 563,
        Name: 'bot_delete_response',
        Module: 'response',
        Description: 'can_delete_response',
        App: 'Virtual Agent',
    },
    BotGetStatisticByMonth: {
        Code: 570,
        Name: 'bot_get_bot_statistic_by_month',
        Module: 'bot_statistic',
        Description: 'can_get_bot_statistic_by_month',
        App: 'Virtual Agent',
    },
    BotCreateFeedback: {
        Code: 580,
        Name: 'bot_create_feedback',
        Module: 'feedbacks',
        Description: 'can_create_feedbacks',
        App: 'Virtual Agent',
    },
    BotViewFeedbackOption: {
        Code: 581,
        Name: 'bot_view_feedback_option',
        Module: 'feedbacks',
        Description: 'can_view_feedback_option',
        App: 'Virtual Agent',
    },
    BotGetPersistentMenu: {
        Code: 590,
        Name: 'bot_get_persistent_menu',
        Module: 'bot_setting',
        Description: 'can_get_persistent_menu',
        App: 'Virtual Agent',
    },
    BotAddPersistentMenu: {
        Code: 591,
        Name: 'bot_add_persistent_menu',
        Module: 'bot_setting',
        Description: 'can_add_persistent_menu',
        App: 'Virtual Agent',
    },
    BotUpdatePersistentMenu: {
        Code: 592,
        Name: 'bot_update_persistent_menu',
        Module: 'bot_setting',
        Description: 'can_update_persistent_menu',
        App: 'Virtual Agent',
    },
    BotDeletePersistentMenu: {
        Code: 593,
        Name: 'bot_delete_persistent_menu',
        Module: 'bot_setting',
        Description: 'can_delete_persistent_menu',
        App: 'Virtual Agent',
    },
    BotSendPersistentMenu: {
        Code: 594,
        Name: 'bot_send_persistent_menu',
        Module: 'bot_setting',
        Description: 'can_send_persistent_menu',
        App: 'Virtual Agent',
    },
    BotDisablePersistentMenu: {
        Code: 595,
        Name: 'bot_disable_persistent_menu',
        Module: 'bot_setting',
        Description: 'can_disable_persistent_menu',
        App: 'Virtual Agent',
    },
    BotGetGetStarted: {
        Code: 596,
        Name: 'bot_get_get_started',
        Module: 'bot_setting',
        Description: 'can_get_greeting',
        App: 'Virtual Agent',
    },
    BotSaveGetStarted: {
        Code: 597,
        Name: 'bot_save_get_started',
        Module: 'bot_setting',
        Description: 'can_get_greeting',
        App: 'Virtual Agent',
    },
    BotSendGetStarted: {
        Code: 598,
        Name: 'bot_send_get_started',
        Module: 'bot_setting',
        Description: 'can_get_greeting',
        App: 'Virtual Agent',
    },
    BotDisableGetStarted: {
        Code: 599,
        Name: 'bot_disable_get_started',
        Module: 'bot_setting',
        Description: 'can_get_greeting',
        App: 'Virtual Agent',
    },
    BotGetGreeting: {
        Code: 600,
        Name: 'bot_get_greeting',
        Module: 'bot_setting',
        Description: 'can_get_greeting',
        App: 'Virtual Agent',
    },
    BotCreateGreeting: {
        Code: 601,
        Name: 'bot_create_greeting',
        Module: 'bot_setting',
        Description: 'can_create_greeting',
        App: 'Virtual Agent',
    },
    BotUpdateGreeting: {
        Code: 602,
        Name: 'bot_update_greeting',
        Module: 'bot_setting',
        Description: 'can_update_greeting',
        App: 'Virtual Agent',
    },
    BotDeleteGreeting: {
        Code: 603,
        Name: 'bot_delete_greeting',
        Module: 'bot_setting',
        Description: 'can_delete_greeting',
        App: 'Virtual Agent',
    },
    BotSendGreeting: {
        Code: 604,
        Name: 'bot_send_greeting',
        Module: 'bot_setting',
        Description: 'can_send_greeting',
        App: 'Virtual Agent',
    },
    BotDisableGreeting: {
        Code: 605,
        Name: 'bot_disable_greeting',
        Module: 'bot_setting',
        Description: 'can_disable_greeting',
        App: 'Virtual Agent',
    },
    BotGetIceBreakers: {
        Code: 606,
        Name: 'bot_disable_ice_breakers',
        Module: 'bot_setting',
        Description: 'can_disable_ice_breakers',
        App: 'Virtual Agent',
    },
    BotCreateIceBreakers: {
        Code: 607,
        Name: 'bot_create_ice_breakers',
        Module: 'bot_setting',
        Description: 'can_create_ice_breakers',
        App: 'Virtual Agent',
    },
    BotUpdateIceBreakers: {
        Code: 608,
        Name: 'bot_update_ice_breakers',
        Module: 'bot_setting',
        Description: 'can_update_ice_breakers',
        App: 'Virtual Agent',
    },
    BotDeleteIceBreakers: {
        Code: 609,
        Name: 'bot_delete_ice_breakers',
        Module: 'bot_setting',
        Description: 'can_delete_ice_breakers',
        App: 'Virtual Agent',
    },
    BotSendIceBreakers: {
        Code: 610,
        Name: 'bot_send_ice_breakers',
        Module: 'bot_setting',
        Description: 'can_send_ice_breakers',
        App: 'Virtual Agent',
    },
    BotDisableIceBreakers: {
        Code: 611,
        Name: 'bot_disable_ice_breakers',
        Module: 'bot_setting',
        Description: 'can_disable_ice_breakers',
        App: 'Virtual Agent',
    },
    BotGetWhitelistedDomains: {
        Code: 612,
        Name: 'bot_get_whitelisted_domains',
        Module: 'bot_setting',
        Description: 'can_get_whitelisted_domains',
        App: 'Virtual Agent',
    },
    BotUpdateWhitelistedDomains: {
        Code: 613,
        Name: 'bot_update_whitelisted_domains',
        Module: 'bot_setting',
        Description: 'can_update_whitelisted_domains',
        App: 'Virtual Agent',
    },
    BotSendWhitelistedDomains: {
        Code: 614,
        Name: 'bot_send_whitelisted_domains',
        Module: 'bot_setting',
        Description: 'can_send_whitelisted_domains',
        App: 'Virtual Agent',
    },
    BotDisableWhitelistedDomains: {
        Code: 615,
        Name: 'bot_disable_whitelisted_domains',
        Module: 'bot_setting',
        Description: 'can_disable_whitelisted_domains',
        App: 'Virtual Agent',
    },
    VqcViewBasicSettings: {
        Code: 700,
        Name: 'vqc_view_basic_settings',
        Module: 'settings',
        Description: 'can_view_basic_settings',
        App: 'Virtual QC',
    },
    VqcViewIntentSettings: {
        Code: 701,
        Name: 'vqc_view_intent_settings',
        Module: 'settings',
        Description: 'can_view_intent_settings',
        App: 'Virtual QC',
    },
    VqcViewConfidenceRangeSettings: {
        Code: 702,
        Name: 'vqc_view_confidence_range_settings',
        Module: 'settings',
        Description: 'can_view_confidence_range_settings',
        App: 'Virtual QC',
    },
    VqcViewAudioChannelSettings: {
        Code: 703,
        Name: 'vqc_view_audio_channel_settings',
        Module: 'settings',
        Description: 'can_view_audio_channel_settings',
        App: 'Virtual QC',
    },
    VqcTrainNlp: {
        Code: 710,
        Name: 'vqc_train_nlp',
        Module: 'nlp_actions',
        Description: 'can_train_nlp',
        App: 'Virtual QC',
    },
    VqcTestSingleSentence: {
        Code: 711,
        Name: 'vqc_test_single_sentence',
        Module: 'nlp_actions',
        Description: 'can_test_single_sentence',
        App: 'Virtual QC',
    },
    VqcTestMultipleSentences: {
        Code: 712,
        Name: 'vqc_test_multiple_sentences',
        Module: 'nlp_actions',
        Description: 'can_test_multiple_sentences',
        App: 'Virtual QC',
    },
    VqcViewNlpOverview: {
        Code: 720,
        Name: 'vqc_view_nlp_overview',
        Module: 'nlp_overview',
        Description: 'can_view_nlp_overview',
        App: 'Virtual QC',
    },
    VqcViewSamples: {
        Code: 730,
        Name: 'vqc_view_samples',
        Module: 'samples',
        Description: 'can_view_samples',
        App: 'Virtual QC',
    },
    VqcCreateSamples: {
        Code: 731,
        Name: 'vqc_create_samples',
        Module: 'samples',
        Description: 'can_create_samples',
        App: 'Virtual QC',
    },
    VqcUpdateSamples: {
        Code: 732,
        Name: 'vqc_update_samples',
        Module: 'samples',
        Description: 'can_update_samples',
        App: 'Virtual QC',
    },
    VqcDeleteSamples: {
        Code: 733,
        Name: 'vqc_delete_samples',
        Module: 'samples',
        Description: 'can_delete_samples',
        App: 'Virtual QC',
    },
    VqcUploadSamples: {
        Code: 734,
        Name: 'vqc_upload_samples',
        Module: 'samples',
        Description: 'can_upload_samples',
        App: 'Virtual QC',
    },
    VqcDowloadSamples: {
        Code: 735,
        Name: 'vqc_dowload_samples',
        Module: 'samples',
        Description: 'can_dowload_samples',
        App: 'Virtual QC',
    },
    VqcViewIntents: {
        Code: 740,
        Name: 'vqc_view_intents',
        Module: 'intents',
        Description: 'can_view_intents',
        App: 'Virtual QC',
    },
    VqcCreateIntents: {
        Code: 741,
        Name: 'vqc_create_intents',
        Module: 'intents',
        Description: 'can_create_intents',
        App: 'Virtual QC',
    },
    VqcUpdateIntents: {
        Code: 742,
        Name: 'vqc_update_intents',
        Module: 'intents',
        Description: 'can_update_intents',
        App: 'Virtual QC',
    },
    VqcDeleteIntents: {
        Code: 743,
        Name: 'vqc_delete_intents',
        Module: 'intents',
        Description: 'can_delete_intents',
        App: 'Virtual QC',
    },
    VqcUploadIntents: {
        Code: 744,
        Name: 'vqc_upload_intents',
        Module: 'intents',
        Description: 'can_upload_intents',
        App: 'Virtual QC',
    },
    VqcCommentIntents: {
        Code: 745,
        Name: 'vqc_comment_intents',
        Module: 'intents',
        Description: 'can_comment_intents',
        App: 'Virtual QC',
    },
    VqcViewEntityTypes: {
        Code: 750,
        Name: 'vqc_view_entity_types',
        Module: 'entity_types',
        Description: 'can_view_entity_types',
        App: 'Virtual QC',
    },
    VqcCreateEntityTypes: {
        Code: 751,
        Name: 'vqc_create_entity_types',
        Module: 'entity_types',
        Description: 'can_create_entity_types',
        App: 'Virtual QC',
    },
    VqcUpdateEntityTypes: {
        Code: 752,
        Name: 'vqc_update_entity_types',
        Module: 'entity_types',
        Description: 'can_update_entity_types',
        App: 'Virtual QC',
    },
    VqcDeleteEntityTypes: {
        Code: 753,
        Name: 'vqc_delete_entity_types',
        Module: 'entity_types',
        Description: 'can_delete_entity_types',
        App: 'Virtual QC',
    },
    VqcViewNlpKeywords: {
        Code: 760,
        Name: 'vqc_view_nlp_keywords',
        Module: 'nlp_keywords',
        Description: 'can_view_nlp_keywords',
        App: 'Virtual QC',
    },
    VqcCreateNlpKeywords: {
        Code: 761,
        Name: 'vqc_create_nlp_keywords',
        Module: 'nlp_keywords',
        Description: 'can_create_nlp_keywords',
        App: 'Virtual QC',
    },
    VqcUpdateNlpKeywords: {
        Code: 762,
        Name: 'vqc_update_nlp_keywords',
        Module: 'nlp_keywords',
        Description: 'can_update_nlp_keywords',
        App: 'Virtual QC',
    },
    VqcDeleteNlpKeywords: {
        Code: 763,
        Name: 'vqc_delete_nlp_keywords',
        Module: 'nlp_keywords',
        Description: 'can_delete_nlp_keywords',
        App: 'Virtual QC',
    },
    VqcUploadNlpKeywords: {
        Code: 764,
        Name: 'vqc_upload_nlp_keywords',
        Module: 'nlp_keywords',
        Description: 'can_upload_nlp_keywords',
        App: 'Virtual QC',
    },
    VqcViewStopWords: {
        Code: 770,
        Name: 'vqc_view_stop_words',
        Module: 'stop_words',
        Description: 'can_view_stop_words',
        App: 'Virtual QC',
    },
    VqcCreateStopWords: {
        Code: 771,
        Name: 'vqc_create_stop_words',
        Module: 'stop_words',
        Description: 'can_create_stop_words',
        App: 'Virtual QC',
    },
    VqcUpdateStopWords: {
        Code: 772,
        Name: 'vqc_update_stop_words',
        Module: 'stop_words',
        Description: 'can_update_stop_words',
        App: 'Virtual QC',
    },
    VqcDeleteStopWords: {
        Code: 773,
        Name: 'vqc_delete_stop_words',
        Module: 'stop_words',
        Description: 'can_delete_stop_words',
        App: 'Virtual QC',
    },
    VqcViewTeenCodes: {
        Code: 780,
        Name: 'vqc_view_teen_codes',
        Module: 'teen_codes',
        Description: 'can_view_teen_codes',
        App: 'Virtual QC',
    },
    VqcCreateTeenCodes: {
        Code: 781,
        Name: 'vqc_create_teen_codes',
        Module: 'teen_codes',
        Description: 'can_create_teen_codes',
        App: 'Virtual QC',
    },
    VqcUpdateTeenCodes: {
        Code: 782,
        Name: 'vqc_update_teen_codes',
        Module: 'teen_codes',
        Description: 'can_update_teen_codes',
        App: 'Virtual QC',
    },
    VqcDeleteTeenCodes: {
        Code: 783,
        Name: 'vqc_delete_teen_codes',
        Module: 'teen_codes',
        Description: 'can_delete_teen_codes',
        App: 'Virtual QC',
    },
    VqcViewTestingHistory: {
        Code: 790,
        Name: 'vqc_view_testing_history',
        Module: 'testing_history',
        Description: 'can_view_testing_history',
        App: 'Virtual QC',
    },
    VqcUpdateTestingHistory: {
        Code: 791,
        Name: 'vqc_update_testing_history',
        Module: 'testing_history',
        Description: 'can_update_testing_history',
        App: 'Virtual QC',
    },
    VqcViewTrainingLogs: {
        Code: 800,
        Name: 'vqc_view_training_logs',
        Module: 'training_logs',
        Description: 'can_view_training_logs',
        App: 'Virtual QC',
    },
    VqcViewQcDashboard: {
        Code: 810,
        Name: 'vqc_view_qc_dashboard',
        Module: 'qc_dashboard',
        Description: 'can_view_qc_dashboard',
        App: 'Virtual QC',
    },
    VqcViewUploadedAudios: {
        Code: 820,
        Name: 'vqc_view_uploaded_audios',
        Module: 'agent_evaluation',
        Description: 'can_view_uploaded_audios',
        App: 'Virtual QC',
    },
    VqcUploadAudios: {
        Code: 821,
        Name: 'vqc_upload_audios',
        Module: 'agent_evaluation',
        Description: 'can_upload_audios',
        App: 'Virtual QC',
    },
    VqcDownloadAudios: {
        Code: 822,
        Name: 'vqc_download_audios',
        Module: 'agent_evaluation',
        Description: 'can_download_audios',
        App: 'Virtual QC',
    },
    VqcViewKpiEstimation: {
        Code: 823,
        Name: 'vqc_view_kpi_estimation',
        Module: 'agent_evaluation',
        Description: 'can_view_kpi_estimation',
        App: 'Virtual QC',
    },
    VqcViewTranscript: {
        Code: 824,
        Name: 'vqc_view_transcript',
        Module: 'agent_evaluation',
        Description: 'can_view_transcript',
        App: 'Virtual QC',
    },
    VqcViewExtractedEntities: {
        Code: 825,
        Name: 'vqc_view_extracted_entities',
        Module: 'agent_evaluation',
        Description: 'can_view_extracted_entities',
        App: 'Virtual QC',
    },
    VqcUpdateScores: {
        Code: 826,
        Name: 'vqc_update_scores',
        Module: 'agent_evaluation',
        Description: 'can_update_scores',
        App: 'Virtual QC',
    },
    VqcAddComments: {
        Code: 827,
        Name: 'vqc_add_comments',
        Module: 'agent_evaluation',
        Description: 'can_add_comments',
        App: 'Virtual QC',
    },
    VqcViewKpis: {
        Code: 830,
        Name: 'vqc_view_kpis',
        Module: 'setup_kpi',
        Description: 'can_view_kpis',
        App: 'Virtual QC',
    },
    VqcCreateKpiGroups: {
        Code: 831,
        Name: 'vqc_create_kpi_groups',
        Module: 'setup_kpi',
        Description: 'can_create_kpi_groups',
        App: 'Virtual QC',
    },
    VqcUpdateKpiGroups: {
        Code: 832,
        Name: 'vqc_update_kpi_groups',
        Module: 'setup_kpi',
        Description: 'can_update_kpi_groups',
        App: 'Virtual QC',
    },
    VqcDeleteKpiGroups: {
        Code: 833,
        Name: 'vqc_delete_kpi_groups',
        Module: 'setup_kpi',
        Description: 'can_delete_kpi_groups',
        App: 'Virtual QC',
    },
    VqcCreateKpis: {
        Code: 834,
        Name: 'vqc_create_kpis',
        Module: 'setup_kpi',
        Description: 'can_create_kpis',
        App: 'Virtual QC',
    },
    VqcUpdateKpis: {
        Code: 835,
        Name: 'vqc_update_kpis',
        Module: 'setup_kpi',
        Description: 'can_update_kpis',
        App: 'Virtual QC',
    },
    VqcActivateKpis: {
        Code: 836,
        Name: 'vqc_activate_kpis',
        Module: 'setup_kpi',
        Description: 'can_activate_kpis',
        App: 'Virtual QC',
    },
    VqcDeactivateKpis: {
        Code: 837,
        Name: 'vqc_deactivate_kpis',
        Module: 'setup_kpi',
        Description: 'can_deactivate_kpis',
        App: 'Virtual QC',
    },
    VqcDeleteKpis: {
        Code: 838,
        Name: 'vqc_delete_kpis',
        Module: 'setup_kpi',
        Description: 'can_delete_kpis',
        App: 'Virtual QC',
    },
    VqcViewUpdatedHistory: {
        Code: 840,
        Name: 'vqc_view_updated_history',
        Module: 'updated_history',
        Description: 'can_view_updated_history',
        App: 'Virtual QC',
    },
    VqcViewCcCallReport: {
        Code: 850,
        Name: 'vqc_view_cc_call_report',
        Module: 'cc_call_report',
        Description: 'can_view_cc_call_report',
        App: 'Virtual QC',
    },
    VqcUploadCcCallReport: {
        Code: 851,
        Name: 'vqc_upload_cc_call_report',
        Module: 'cc_call_report',
        Description: 'can_upload_cc_call_report',
        App: 'Virtual QC',
    },
    VqcViewAgentReport: {
        Code: 860,
        Name: 'vqc_view_agent_report',
        Module: 'report',
        Description: 'can_view_agent_report',
        App: 'Virtual QC',
    },
    VqcViewErrorReport: {
        Code: 861,
        Name: 'vqc_view_error_report',
        Module: 'report',
        Description: 'can_view_error_report',
        App: 'Virtual QC',
    },
    VqcExportReportToCsv: {
        Code: 862,
        Name: 'vqc_export_report_to_csv',
        Module: 'report',
        Description: 'can_export_report_to_csv',
        App: 'Virtual QC',
    },
    VqcViewMembers: {
        Code: 870,
        Name: 'vqc_view_members',
        Module: 'permission_settings',
        Description: 'can_view_members',
        App: 'Virtual QC',
    },
    VqcInviteNewMember: {
        Code: 871,
        Name: 'vqc_invite_new_member',
        Module: 'permission_settings',
        Description: 'can_invite_new_member',
        App: 'Virtual QC',
    },
    VqcUpdateMemberRole: {
        Code: 872,
        Name: 'vqc_update_member_role',
        Module: 'permission_settings',
        Description: 'can_update_member_role',
        App: 'Virtual QC',
    },
    LabelboxLabelTranscripts: {
        Code: 1000,
        Name: 'labelbox_label_transcripts',
        Module: 'transcript',
        Description: 'can_label_transcripts',
        App: 'Labelbox',
    },
    LabelboxViewTranscripts: {
        Code: 1001,
        Name: 'labelbox_view_transcripts',
        Module: 'transcript',
        Description: 'can_view_transcripts',
        App: 'Labelbox',
    },
    LabelboxUploadAudios: {
        Code: 1002,
        Name: 'labelbox_upload_audios',
        Module: 'transcript',
        Description: 'can_upload_audios',
        App: 'Labelbox',
    },
    LabelboxViewCorectionWords: {
        Code: 1010,
        Name: 'labelbox_view_corection_words',
        Module: 'correction_dictionary',
        Description: 'can_view_corection_words',
        App: 'Labelbox',
    },
    LabelboxCreateCorrectionWords: {
        Code: 1011,
        Name: 'labelbox_create_correction_words',
        Module: 'correction_dictionary',
        Description: 'can_create_correction_words',
        App: 'Labelbox',
    },
    LabelboxUpdateCorrectionWords: {
        Code: 1012,
        Name: 'labelbox_update_correction_words',
        Module: 'correction_dictionary',
        Description: 'can_update_correction_words',
        App: 'Labelbox',
    },
    LabelboxDeleteCorrectionWords: {
        Code: 1013,
        Name: 'labelbox_delete_correction_words',
        Module: 'correction_dictionary',
        Description: 'can_delete_correction_words',
        App: 'Labelbox',
    },
    LabelboxViewDataReport: {
        Code: 1020,
        Name: 'labelbox_view_data_report',
        Module: 'report',
        Description: 'can_view_data_report',
        App: 'Labelbox',
    },
    LabelboxViewUserReport: {
        Code: 1021,
        Name: 'labelbox_view_user_report',
        Module: 'report',
        Description: 'can_view_user_report',
        App: 'Labelbox',
    },
    LabelboxExportReportToCsv: {
        Code: 1022,
        Name: 'labelbox_export_report_to_csv',
        Module: 'report',
        Description: 'can_export_report_to_csv',
        App: 'Labelbox',
    },
    LabelboxExportLabeledData: {
        Code: 1030,
        Name: 'labelbox_export_labeled_data',
        Module: 'export',
        Description: 'can_export_labeled_data',
        App: 'Labelbox',
    },
    LiveChatGetRoom: {
        Code: 1200,
        Name: 'livechat_get_room',
        Module: 'room',
        Description: 'get_data_room',
        App: 'Livechat',
    },
    LivechatGetListRooms: {
        Code: 1201,
        Name: 'livechat_get_list_rooms',
        Module: 'room',
        Description: 'get_list_rooms',
        App: 'Livechat',
    },
    LivechatEditRoom: {
        Code: 1202,
        Name: 'livechat_edit_room',
        Module: 'room',
        Description: 'edit_room',
        App: 'Livechat',
    },
    LivechatGetMessages: {
        Code: 1210,
        Name: 'livechat_get_messages',
        Module: 'message',
        Description: 'get_messages',
        App: 'Livechat',
    },
    LivechatGetNotifications: {
        Code: 1220,
        Name: 'livechat_get_notifications',
        Module: 'notification',
        Description: 'get_list_notifications',
        App: 'Livechat',
    },
    LivechatEditNotification: {
        Code: 1221,
        Name: 'livechat_edit_notification',
        Module: 'notification',
        Description: 'edit_notification',
        App: 'Livechat',
    },
    LivechatGetTags: {
        Code: 1230,
        Name: 'livechat_get_tags',
        Module: 'tag',
        Description: 'get_list_tags',
        App: 'Livechat',
    },
    LivechatGetBotStatistic: {
        Code: 1240,
        Name: 'livechat_get_bot_statistic',
        Module: 'bot-statistic',
        Description: 'can_get_bot_statistic',
        App: 'Livechat',
    },
    LivechatSaveBotStatistic: {
        Code: 1241,
        Name: 'livechat_save_bot_statistic',
        Module: 'bot-statistic',
        Description: 'can_save_bot_statistic',
        App: 'Livechat',
    },
});
