
const HttpMethod = Object.freeze({
    GET: 'GET',
    POST: 'POST',
    PUT: 'PUT',
    DELETE: 'DELETE',
});
const ResponseMessage = Object.freeze({
    NotFoundDiscount: "Cannot found this discount",
    SavedSuccessfully: "saved_successfully",
    DeletedSuccessfully: "Deleted successfully",
    SentSuccessfully: "Sent successfully",
    SomethingGoesWrong: "Oops, something goes wrong",
    RegisterSuccessfully: "Register successfully, please verify your email before login",
    UsernameExistingError: "Username is existing",
    LinkNotExistingError: "Oops, your link is not existing",
    VerifyEmailSuccessfully: "Verify email successfully. Thanks for be our partner",
    EmailVerified: "Email is verified",
    AccountNotExisting: "Opps, this account is not existing",
    CheckEmailMessage: "Check your email to get new password",
    OldPasswordNotCorrect: "Opps, old password is not correct",
    ChangedPasswordSuccessfully: "Changed password successfully",
    AccessDenied: "Access Denied",
    TokenNull: "Token is null",
    TokenValid: "Token is valid",
    TokenInvalid: "Token is invalid",
    TokenExpired: "Token is expired",
    ProviderIDInvalid: "Provider ID is invalid",
    CustomerIDInvalid: "Customer ID is invalid",
    NotFoundProvider: "Cannot found this provider",
    NotFoundPlaceId: "Cannot found this placeId",
    NotFoundAccount: "Cannot found this account",
    NotFoundShip: "Cannot found this ship",
    NotFoundUnit: "Cannot found this unit",
    NotAllowSendNoWaitingMessage: "Cannot update the non-waiting message",
    NotAllowCancelNonePendingShip: "Cannot cancel inprogress ship",
    NotAllowAcceptOrRefuseInprogressShip: "not_allow_accept_or_refuse_in_progress",
    NotAllowCancelNonePendingBook: "Cannot cancel inprogress book",
    NotAllowAcceptOrRefuseInprogressBook: "Đơn hàng đã được xử lý. Thao tác của bạn bị hủy bỏ.",
    QRCodeUsed: "this-qr-code-was-used",
    NoActivePromotion: "No active promotion",
    MenuNameExistingError: "Menu is existing",
    NotFoundFbIDs: "No fbId found",
    InvalidMessage: "Invalid message",
    NotFoundLoyaltyProgram: "Loyalty program not found",
    AccountExpiredFreeTrial: 'Account is expired free trial',
    InternalServerError: 'Internal Server Error',
    BadRequest: 'Bad Request',
    Unauthorized: 'Unauthorized',
    Forbidden: 'Forbidden',
    ResourceNotFound: 'Resource Not Found',
    ServiceUnavilable: 'Service Unavilable',
});

export {HttpMethod,ResponseMessage};